[package]
name = "udf-error"
version = "0.1.0"
authors = ["Jeff Davis <jdavis@postgresql.org>"]
edition = "2018"

[dependencies]
postgres-extension = { path = "../.." }
postgres-extension-macro = { path = "../../postgres-extension-macro" }

[lib]
crate-type = ["cdylib"]
test = false
bench = false

[[bin]]
name = "libinstall"
